[supervisord]
nodaemon=true
user=root

[program:mosquitto]
command=/usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
priority=1
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:mg-gateway]
command=/usr/src/gateway/.venv/bin/python /usr/src/gateway/main.py
directory=/usr/src/gateway
priority=10
autorestart=true
startretries=1000
startsecs=5
environment=MQTT_URI="tcp://127.0.0.1:1883"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:yemot-bridge]
command=/usr/src/gateway/.venv/bin/python /usr/src/bridge/yemot_bridge.py
priority=10
autorestart=true
startretries=1000
startsecs=5
environment=MQTT_HOST="127.0.0.1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
